In [5]:
#👉 scikit-learn (sklearn) = Python library used for Machine Learning
import pandas as pd
from sklearn.model_selection import train_test_split

data = {
    "area":[1000,1500,2000,2500],
    "bedrooms":[2,3,3,4],
    "price":[3,4.5,6,7]
}

df= pd.DataFrame(data)

In [6]:
df

   area  bedrooms  price
0  1000         2    3.0
1  1500         3    4.5
2  2000         3    6.0
3  2500         4    7.0

In [26]:
#axis=1 operate on columns , axis=0 operate on rows

#select entire table except price column
# features (input)
X = df.drop("price", axis=1)

#select only price column from table
# target (output)
y = df["price"]

In [27]:
#test_size=0.2 means 20% data testing and 80% data training
#random_state=42 means same split and results everytime
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("X_train:\n", X_train)
print("\n X_test:\n", X_test)

X_train:
    area  bedrooms
3  2500         4
0  1000         2
2  2000         3

 X_test:
    area  bedrooms
1  1500         3

In [38]:
#holds everything except price columns
X_train

   area  bedrooms
3  2500         4
0  1000         2
2  2000         3

In [35]:
#holds just the price column
X_test

   area  bedrooms
1  1500         3